### ISSUE TITLE
When you run Stow how does it know where to place each file?

### ISSUE THREAD

**Issue by tomer-ben-david** [ralish/dotfiles#1]
What if a dotfile should be placed under a different directory like what if I have a dotfile that should be installed under `~/mysoftware/.somedotfile`? do you have such an example?

**Comment by ralish** [comment]
Easy, just mirror the directory structure relative to your home directory inside the dotfiles directory for that program. So in your example, we might have a directory `mysoftware/mysoftware/.somedotfile` in the `dotfiles` directory. When `dot-manage` is run (or `stow` directly), the created symlink will be `~/mysoftware/.somedotfile`.

I have several dotfiles that have this requirement. Examples include `vim`, `htop`, and `cpan`.
